.TH HELLO 1 "April 2026" "2.0" "Hello User Manual"
.SH NAME
hello \- prints a customized greeting
.SH SYNOPSIS
.B hello
.SH DESCRIPTION
.B hello 
is a simple shell script that prints a customized greeting to the terminal. This project was created to understand the basics of RPM package development.
It reads configuration from /etc/hello.conf.
.SH FILES
.I /etc/hello.conf
.SH AUTHOR
UltraGen <ultragenesis24@gmail.com>
